// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Server.Infrastructure.Data;

#nullable disable

namespace Server.WebAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251130134151_AddPlayerPartyPokemonRelationship")]
    partial class AddPlayerPartyPokemonRelationship
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PlayerPartyPokemon", b =>
                {
                    b.Property<int>("playerPartyId")
                        .HasColumnType("int");

                    b.Property<string>("pokemonId")
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("playerPartyId", "pokemonId");

                    b.HasIndex("pokemonId");

                    b.ToTable("PlayerPartyPokemon", (string)null);
                });

            modelBuilder.Entity("PokemonMove", b =>
                {
                    b.Property<int>("pokemonSpeciesId")
                        .HasColumnType("int");

                    b.Property<int>("moveId")
                        .HasColumnType("int");

                    b.HasKey("pokemonSpeciesId", "moveId");

                    b.HasIndex("moveId");

                    b.ToTable("PokemonMove", (string)null);
                });

            modelBuilder.Entity("PokemonMove2", b =>
                {
                    b.Property<string>("pokemonId")
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("moveId")
                        .HasColumnType("int");

                    b.HasKey("pokemonId", "moveId");

                    b.HasIndex("moveId");

                    b.ToTable("PokemonMoveInstance", (string)null);
                });

            modelBuilder.Entity("Server.Domain.Entities.Move", b =>
                {
                    b.Property<int>("MoveId")
                        .HasColumnType("int")
                        .HasColumnName("moveId");

                    b.Property<int>("Accuracy")
                        .HasColumnType("int")
                        .HasColumnName("accuracy");

                    b.Property<int>("Ailment")
                        .HasMaxLength(63)
                        .HasColumnType("int")
                        .HasColumnName("ailment");

                    b.Property<int>("AilmentChance")
                        .HasColumnType("int")
                        .HasColumnName("ailmentChance");

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<int>("CritRate")
                        .HasColumnType("int")
                        .HasColumnName("critRate");

                    b.Property<int>("DamageClass")
                        .HasColumnType("int");

                    b.Property<int>("Drain")
                        .HasColumnType("int")
                        .HasColumnName("drain");

                    b.Property<int>("Healing")
                        .HasColumnType("int")
                        .HasColumnName("healing");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("name");

                    b.Property<int>("Power")
                        .HasColumnType("int")
                        .HasColumnName("power");

                    b.Property<int>("Pp")
                        .HasColumnType("int")
                        .HasColumnName("pp");

                    b.Property<int>("Priority")
                        .HasColumnType("int")
                        .HasColumnName("priority");

                    b.Property<int>("RankChance")
                        .HasColumnType("int")
                        .HasColumnName("rankChance");

                    b.Property<string>("RankTarget")
                        .IsRequired()
                        .HasMaxLength(63)
                        .HasColumnType("nvarchar(63)")
                        .HasColumnName("rankTarget");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(63)
                        .HasColumnType("nvarchar(63)")
                        .HasColumnName("type");

                    b.HasKey("MoveId");

                    b.ToTable("Move", (string)null);
                });

            modelBuilder.Entity("Server.Domain.Entities.Player", b =>
                {
                    b.Property<string>("PlayerId")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("playerId");

                    b.Property<string>("IconUrl")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("iconUrl");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("name");

                    b.HasKey("PlayerId");

                    b.ToTable("Player", (string)null);
                });

            modelBuilder.Entity("Server.Domain.Entities.PlayerParty", b =>
                {
                    b.Property<int>("PlayerPartyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("playerPartyId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PlayerPartyId"));

                    b.Property<string>("PlayerId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("playerId");

                    b.HasKey("PlayerPartyId");

                    b.HasIndex("PlayerId");

                    b.ToTable("PlayerParty", (string)null);
                });

            modelBuilder.Entity("Server.Domain.Entities.Pokemon", b =>
                {
                    b.Property<string>("PokemonId")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("pokemonId");

                    b.Property<int>("Exp")
                        .HasColumnType("int")
                        .HasColumnName("exp");

                    b.Property<int>("Level")
                        .HasColumnType("int")
                        .HasColumnName("level");

                    b.Property<int>("pokemonSpeciesId")
                        .HasColumnType("int");

                    b.HasKey("PokemonId");

                    b.HasIndex("pokemonSpeciesId");

                    b.ToTable("Pokemon", (string)null);
                });

            modelBuilder.Entity("Server.Domain.Entities.PokemonSpecies", b =>
                {
                    b.Property<int>("PokemonSpeciesId")
                        .HasColumnType("int")
                        .HasColumnName("pokemonSpeciesId");

                    b.Property<string>("BackImage")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("backImage");

                    b.Property<int>("BaseAttack")
                        .HasColumnType("int")
                        .HasColumnName("baseAttack");

                    b.Property<int>("BaseDefence")
                        .HasColumnType("int")
                        .HasColumnName("baseDefense");

                    b.Property<int>("BaseHp")
                        .HasColumnType("int")
                        .HasColumnName("baseHp");

                    b.Property<int>("BaseSpecialAttack")
                        .HasColumnType("int")
                        .HasColumnName("baseSpecialAttack");

                    b.Property<int>("BaseSpecialDefence")
                        .HasColumnType("int")
                        .HasColumnName("baseSpecialDefense");

                    b.Property<int>("BaseSpeed")
                        .HasColumnType("int")
                        .HasColumnName("baseSpeed");

                    b.Property<int>("EvolveLevel")
                        .HasColumnType("int")
                        .HasColumnName("evolveLevel");

                    b.Property<string>("FrontImage")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("frontImage");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("name");

                    b.Property<string>("Type1")
                        .IsRequired()
                        .HasMaxLength(63)
                        .HasColumnType("nvarchar(63)")
                        .HasColumnName("type1");

                    b.Property<string>("Type2")
                        .HasMaxLength(63)
                        .HasColumnType("nvarchar(63)")
                        .HasColumnName("type2");

                    b.HasKey("PokemonSpeciesId");

                    b.ToTable("PokemonSpecies", (string)null);
                });

            modelBuilder.Entity("PlayerPartyPokemon", b =>
                {
                    b.HasOne("Server.Domain.Entities.PlayerParty", null)
                        .WithMany()
                        .HasForeignKey("playerPartyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Server.Domain.Entities.Pokemon", null)
                        .WithMany()
                        .HasForeignKey("pokemonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PokemonMove", b =>
                {
                    b.HasOne("Server.Domain.Entities.Move", null)
                        .WithMany()
                        .HasForeignKey("moveId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Server.Domain.Entities.PokemonSpecies", null)
                        .WithMany()
                        .HasForeignKey("pokemonSpeciesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PokemonMove2", b =>
                {
                    b.HasOne("Server.Domain.Entities.Move", null)
                        .WithMany()
                        .HasForeignKey("moveId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Server.Domain.Entities.Pokemon", null)
                        .WithMany()
                        .HasForeignKey("pokemonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Server.Domain.Entities.Move", b =>
                {
                    b.OwnsOne("Server.Domain.Entities.Rank", "Rank", b1 =>
                        {
                            b1.Property<int>("MoveId")
                                .HasColumnType("int");

                            b1.Property<int>("Accuracy")
                                .HasColumnType("int")
                                .HasColumnName("rankAccuracy");

                            b1.Property<int>("Attack")
                                .HasColumnType("int")
                                .HasColumnName("rankAttack");

                            b1.Property<int>("Defence")
                                .HasColumnType("int")
                                .HasColumnName("rankDefence");

                            b1.Property<int>("Evasion")
                                .HasColumnType("int")
                                .HasColumnName("rankEvasion");

                            b1.Property<int>("SpecialAttack")
                                .HasColumnType("int")
                                .HasColumnName("rankSpecialAttack");

                            b1.Property<int>("SpecialDefence")
                                .HasColumnType("int")
                                .HasColumnName("rankSpecialDefence");

                            b1.Property<int>("Speed")
                                .HasColumnType("int")
                                .HasColumnName("rankSpeed");

                            b1.HasKey("MoveId");

                            b1.ToTable("Move");

                            b1.WithOwner()
                                .HasForeignKey("MoveId");
                        });

                    b.OwnsMany("Server.Domain.Entities.StatChange", "StatChanges", b1 =>
                        {
                            b1.Property<int>("MoveId")
                                .HasColumnType("int");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<int>("Change")
                                .HasColumnType("int")
                                .HasColumnName("change");

                            b1.Property<string>("Stat")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("stat");

                            b1.HasKey("MoveId", "Id");

                            b1.ToTable("MoveStatChange", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("MoveId");
                        });

                    b.Navigation("Rank")
                        .IsRequired();

                    b.Navigation("StatChanges");
                });

            modelBuilder.Entity("Server.Domain.Entities.PlayerParty", b =>
                {
                    b.HasOne("Server.Domain.Entities.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("Server.Domain.Entities.Pokemon", b =>
                {
                    b.HasOne("Server.Domain.Entities.PokemonSpecies", "Species")
                        .WithMany()
                        .HasForeignKey("pokemonSpeciesId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Species");
                });
#pragma warning restore 612, 618
        }
    }
}
